name: Build and Deploy CV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: cv
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build CV
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ env.FILE }}
          working_directory: ${{ env.DIR }}

      - name: Move PDF to artifacts folder
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download CV PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: cv.pdf
          path: github_artifacts/

      - name: Move PDF to deployment folder
        run: mkdir -p github_deploy && mv github_artifacts/cv.pdf github_deploy/

      - name: Copy index.html and CNAME
        run: |
          cp index.html github_deploy/ || true
          cp CNAME github_deploy/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: true
